#Auth
#Login
# @name login
POST http://localhost:5062/auth/login
Content-Type: application/json

{
    "username": "redha User",
    "password": "pass12345"
}

###
#Refresh token
POST http://localhost:5062/auth/refresh
Cookie: {{login.response.headers.Set-Cookie}}


###
#Logout
PUT http://localhost:5062/auth/logout
Cookie: {{login.response.headers.Set-Cookie}}


# post
###
GET http://localhost:5062/post?page=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6IjRhZmRlYTZiLTc5MTktNDM5OS05NDFjLThlOWRlM2JhNTIyNyIsImV4cCI6MTc3Mzc2NTc0NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.e2S2eDwIhV_g7A3SnT6K0rblDVXMHkKNQ8ED5RIKIg4


###
GET http://localhost:5062/post/98bfa8d4-1048-440c-a322-0afc96dc4807
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6IjRhZmRlYTZiLTc5MTktNDM5OS05NDFjLThlOWRlM2JhNTIyNyIsImV4cCI6MTc3Mzc2NTc0NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.e2S2eDwIhV_g7A3SnT6K0rblDVXMHkKNQ8ED5RIKIg4


###
POST http://localhost:5062/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6IjRhZmRlYTZiLTc5MTktNDM5OS05NDFjLThlOWRlM2JhNTIyNyIsImV4cCI6MTc3Mzc2NTc0NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.e2S2eDwIhV_g7A3SnT6K0rblDVXMHkKNQ8ED5RIKIg4

{
    "content": "Post terakhir"
}

###
POST http://localhost:5062/post/upvote/98bfa8d4-1048-440c-a322-0afc96dc4807
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6IjRhZmRlYTZiLTc5MTktNDM5OS05NDFjLThlOWRlM2JhNTIyNyIsImV4cCI6MTc3Mzc2NTc0NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.e2S2eDwIhV_g7A3SnT6K0rblDVXMHkKNQ8ED5RIKIg4


###
POST http://localhost:5062/post/downvote/98bfa8d4-1048-440c-a322-0afc96dc4807
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6IjRhZmRlYTZiLTc5MTktNDM5OS05NDFjLThlOWRlM2JhNTIyNyIsImV4cCI6MTc3Mzc2NTc0NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.e2S2eDwIhV_g7A3SnT6K0rblDVXMHkKNQ8ED5RIKIg4

###
PUT http://localhost:5062/post/ab9ea47e-0845-434d-93cd-c3834e96da62
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6ImQzMzNhZWZmLTRhYmQtNDNiOC1hZDAwLTEzOGQ5OGQxOWYzMiIsImV4cCI6MTc3Mzc1NzI1NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.jfre0O3-odtbpI79r9VERmFTqF9fGrIeQXhDeDcGnyQ

{
    "content": "Updatee"
}

###
DELETE http://localhost:5062/post/8f7837a7-63fc-4268-a182-c54c71d75e1b