#Auth
#Login
# @name login
POST http://localhost:5062/auth/login
Content-Type: application/json

{
    "username": "redha User",
    "password": "pass12345"
}

###
#Refresh token
POST http://localhost:5062/auth/refresh
Cookie: {{login.response.headers.Set-Cookie}}

###
#Logout
PUT http://localhost:5062/auth/logout
Cookie: {{login.response.headers.Set-Cookie}}

# Profile
###
GET http://localhost:5062/profile/92e7cf60-ba85-43f3-b097-cb2437c8d4bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6ImFiMTlkZmI4LTUyNmYtNDk1Mi05ZmNmLWI5ZjgxMDExMGM1ZSIsImV4cCI6MTc3Mzc2NDMzNSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.Au_cNp5_din1RDuSbG3giBuxuKkZ-E-g3_JQzj1K4zg


###
POST http://localhost:5062/profile/92e7cf60-ba85-43f3-b097-cb2437c8d4bd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6ImFiMTlkZmI4LTUyNmYtNDk1Mi05ZmNmLWI5ZjgxMDExMGM1ZSIsImV4cCI6MTc3Mzc2NDMzNSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.Au_cNp5_din1RDuSbG3giBuxuKkZ-E-g3_JQzj1K4zg

{
    "fullName": "Muhammad Reda",
    "age": 23
}

###
PUT http://localhost:5062/profile/92e7cf60-ba85-43f3-b097-cb2437c8d4bd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU3Y2Y2MC1iYTg1LTQzZjMtYjA5Ny1jYjI0MzdjOGQ0YmQiLCJlbWFpbCI6InJlZGhhdXNlckBlbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6ImFiMTlkZmI4LTUyNmYtNDk1Mi05ZmNmLWI5ZjgxMDExMGM1ZSIsImV4cCI6MTc3Mzc2NDMzNSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDYyIn0.Au_cNp5_din1RDuSbG3giBuxuKkZ-E-g3_JQzj1K4zg

{
    "fullName": "Muhammad Reda",
    "age": 23,
    "phone": "+6285176981101",
    "address": "Pekanbaru"
}

###
DELETE http://localhost:5062/profile/8f7837a7-63fc-4268-a182-c54c71d75e1b